apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: fission
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: fission-data

